### ISSUE TITLE
Can't run the local server

### ISSUE THREAD

**Issue by jlweb58** [ramzan-zafar/check24-web#1]
When I try to start it (as described in the README) I get the following error (on MacOS):
You seem to not be depending on "@angular/core" and/or "rxjs". This is an error.

**Comment by ramzan-zafar** [comment]
Try using command npm link and then the said command

**Comment by jlweb58** [comment]
Works after npm build (the proxy file name in the README is incorrect, it's proxy.conf.json)

**Comment by ramzan-zafar** [comment]
Thanks for mentioning, i have updated the documentation.
